blogproject/blog/urls.py
from django.conf.urls import url
from . import views


# 告诉 django 这个 urls.py 模块是属于 blog 应用
app_name = 'blog'
urlpatterns = [
            url(r'^$', views.index, name="index"),
            url(r'^post/(?P<pk>[0-9]+)/$', views.detail, name="detail"),
            url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.archives, name="archives"),
            url(r'^category/(?P<pk>[0-9]+)/$', views.category, name="category"),
            url(r'^tags/(?P<pk>[0-9]+)/$', views.tags, name="tags"),
            url(r'^search/$', views.search, name="search"),
        ]

blogproject/blogproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('blog.urls')),
    url(r'^usercenter/', include('usercenter.urls')),
]

blogproject/usercenter/urls.py
from django.conf.urls import url, include
from . import views


# app_name = "usercenter"
urlpatterns = [
    url(r'^register$', views.register, name="register"),
    url(r'^activate/(?P<code>\w+)', views.activate, name="activate"),
    url(r'^accounts/', include("django.contrib.auth.urls")),
]

blogproject/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.six import python_2_unicode_compatible
from django.urls import reverse
# Create your models here.


# 文章分类
@python_2_unicode_compatible
class Category(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        verbose_name = "分类"
        verbose_name_plural = verbose_name

    # 装饰器为了兼容python2
    def __str__(self):
        return self.name


# 文章标签
@python_2_unicode_compatible
class Tag(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        verbose_name = "标签"
        verbose_name_plural = verbose_name

    # 装饰器为了兼容python2
    def __str__(self):
        return self.name


# 文章
@python_2_unicode_compatible
class Post(models.Model):
    # 文章标题
    title = models.CharField(max_length=80)
    # 文章内容
    body = models.TextField()
    # 存储文章创建时间和最后更新时间
    create_time = models.DateTimeField(auto_now_add=True)
    modified_time = models.DateTimeField(auto_now=True)

    # 文章摘要，可以为空
    excerpt = models.CharField(max_length=200, blank=True)

    # 分类与标签，使用外键,一篇文章可以对应多个标签，一个标签也可以
    # 对应多篇文章，使用ManyToManyField
    category = models.ForeignKey(Category)
    tags = models.ManyToManyField(Tag, blank=True)

    views = models.PositiveIntegerField(default=1)

    # 文章作者
    author = models.ForeignKey(User)

    def __str__(self):
        return self.title

    # blog:detail表示blog应用下的name=detail函数
    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'pk': self.pk})

    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])

    class Meta:
        verbose_name = "文章"
        verbose_name_plural = verbose_name

blogproject/usercenter/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class ActivateCode(models.Model):
    user = models.ForeignKey(User, verbose_name="用户")
    code = models.CharField("激活码", max_length=100)

    expire_timestamp = models.DateTimeField()

    create_timestamp = models.DateTimeField(auto_now_add=True)
    last_update_timestamp = models.DateTimeField(auto_now=True)

blogproject/blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Category, Tag
from django.conf import settings
from utils.paginator import paginate_queryset
# Create your views here.


def index(request):
    post_list = Post.objects.all().order_by("-id")
    page_no = int(request.GET.get("page_no", "1"))
    page_articles, pagination_data = paginate_queryset(post_list, page_no)
    return render(request, 'blog/index.html', context={
        'post_list': page_articles, 'pagination_data': pagination_data}
    )


def detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.increase_views()
    return render(request, 'blog/detail.html', context={'post': post})


# 处理文章归档
def archives(request, year, month):
    post_list = Post.objects.filter(create_time__year=year, create_time__month=month)
    return render(request, "blog/index.html", context={"post_list": post_list})


# 处理文章标签
def category(request, pk):
    cate = get_object_or_404(Category, pk=pk)
    post_list = Post.objects.filter(category=cate).order_by("id")
    page_no = int(request.GET.get("page_no", "1"))
    page_articles, pagination_data = paginate_queryset(post_list, page_no)
    return render(request, "blog/index.html", context={"post_list": page_articles,
        "pagination_data": pagination_data})


def tags(request, pk):
    label = get_object_or_404(Tag, pk=pk)
    post_list = Post.objects.filter(tags=label).order_by("-id")
    page_no = int(request.GET.get("page_no", "1"))
    page_articles, pagination_data = paginate_queryset(post_list, page_no)
    return render(request, "blog/index.html", context={"post_list": page_articles,
        "pagination_data": pagination_data})


def global_settings(request):
    return {
            "SITE_NAME": settings.SITE_NAME,
            "SITE_DESC": settings.SITE_DESC,
            "CONNECT": settings.CONNECT,
    }


def search(request):
    key = request.GET.get("key")
    err_msg = ""

    if not key:
        err_msg = "请输入关键词"
        return render(request, 'blog/errors.html', {"err_msg": err_msg})

    post_list = Post.objects.filter(title__icontains=key)
    return render(request, 'blog/results.html', {"err_msg": err_msg, "post_list": post_list})

blogproject/usercenter/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
import uuid
import datetime
from django.utils import timezone
from django.core.mail import send_mail
from .models import ActivateCode
# Create your views here.


def register(request):
    err = ''
    if request.method == "GET":
        return render(request, "usercenter/register.html")
    else:
        name = request.POST['username'].strip()
        passwd = request.POST['passwd'].strip()
        re_passwd = request.POST['re_passwd'].strip()
        email = request.POST['email'].strip()

        if not name or not passwd or not re_passwd or not email:
            err = "字段均不能为空"
            return render(request, 'usercenter/register.html', {'msg': err})

        if passwd != re_passwd:
            err = "两次密码输入不一致，请重新输入"
            return render(request, 'usercenter/register.html', {'msg': err})

        if len(passwd) < 8:
            err = "密码长度必须大于8"
            return render(request, 'usercenter/register.html', {'msg': err})

        if User.objects.filter(username=name).count() > 0:
            err = "用户名已存在"
            return render(request, 'usercenter/register.html', {'msg': err})

        if User.objects.filter(email=email).count() > 0:
            err = "当前邮箱已经注册"
            return render(request, "usercenter/register.html", {'msg': err})

        user = User.objects.create_user(name, email, passwd)
        user.is_active = False
        user.save()
        # 生成激活码
        new_code = str(uuid.uuid4()).replace('-', '')
        # 设置激活码过期时间
        expire_time = timezone.now() + datetime.timedelta(days=2)

        code_record = ActivateCode(user=user, code=new_code, expire_timestamp=expire_time)
        code_record.save()

        activate_link = "http://%s/usercenter/activate/%s" % (request.get_host(), new_code)
        activate_email = '''点击<a href="%s">这里</a>激活''' % activate_link

        send_mail(subject='[Bazinga]激活邮件',
                message='点击链接激活%s' % activate_link,
                html_message=activate_email,
                from_email='1137048513@qq.com',
                recipient_list=[email],
                fail_silently=False,
            )

        return render(request, "usercenter/register_success.html", {"msg": "注册成功，请前往邮箱激活"})


def activate(request, code):
    # 找到注册时创建的实例
    acts = ActivateCode.objects.filter(code=code, expire_timestamp__gte=timezone.now())
    if acts.count() > 0:
        code_record = acts[0]
        code_record.user.is_active = True
        code_record.save()
        return render(request, "usercenter/activate_status.html", {'msg': "激活成功"})
    return render(request, "usercenter/activate_status.html", {'msg': "激活失败"})

blogproject/templates/base.html
{% load blog_tags %}
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <!--[if IE]>
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <![endif]-->
        <title>{{SITE_NAME}}</title>
    <!-- BOOTSTRAP CORE STYLE CSS -->
    <link rel="stylesheet" href="http://picturebag.qiniudn.com/monokai.css">
    {% load staticfiles %}
    <link href="{% static 'blog/css/bootstrap.css' %}" rel="stylesheet" />
    <!-- FONTAWESOME STYLE CSS -->
    <link href="{% static 'blog/css/font-awesome.css' %}" rel="stylesheet" />
    <!-- CUSTOM STYLE CSS -->
    <link href="{% static 'blog/css/style.css' %}" rel="stylesheet" />
    <link href="{% static 'blog/css/friendly.css' %}" rel="stylesheet" />
    <link href="{% static 'blog/css/monokai.css' %}" rel="stylesheet" />
    <link href="https://apps.bdimg.com/libs/highlight.js/9.1.0/styles/monokai-sublime.min.css" rel="stylesheet">
    <script src="http://apps.bdimg.com/libs/highlight.js/9.1.0/highlight.min.js"></script>
    <script>hljs.initHighlightingOnLoad();</script>
</head>
<body>


    <section class="header-section">
        <div class="container">
            <div class="row">
							<div class="header-nav">
              <div class="nav pull-right">
                <a href="{% url "blog:index" %}">首 页</a>&nbsp;&nbsp;
                <a href="#">分 类</a>&nbsp;&nbsp;
                <a href="#">标 签</a>&nbsp;&nbsp;
                <a href="#">关于</a>&nbsp;&nbsp;
                {% if user.is_authenticated %}
                <a href="/usercenter/accounts/password_change">{{user.username}}</a>
                <a href="/usercenter/accounts/logout">注销</a>
              {% else %}
              <a href="/usercenter/accounts/login" >注册/登陆</a>
              {% endif %}
              </div>
             </div>
				    </div>
            <div class="row">
                <div class="col-md-2">
                  <a href="{% url "blog:index"%}"><img src="{% static 'blog/img/person.jpg' %}" class="img-circle img-responsive" alt="点击图片返回首页"/></a>
                </div>
                <div class="col-md-5 text-center">
                    <h1><strong>Colin Hu </strong></h1>
                    <h4>Blogger & Coder</h4>
                </div>
                <div class="col-md-5">
                    <h3>WHO M I :</h3>

                    {{SITE_DESC}}<br />
                    You can reach me at <i><strong>{{CONNECT}}</strong></i>
                </div>
            </div>
        </div>
    </section>
    <!--HOME SECTION END-->

    <!--section>
        <div class="container">
            <div class="row">
                <div class="col-md-2 spon-txt">
                    <span><a href="{% url "blog:index" %}">HOME/首页</a></span>
                </div>
                <div class="col-md-10">
                  <img src="{% static 'blog/img/clients.png' %}" alt="" class="img-rounded img-responsive" />
                </div>


            </div>
        </div>
    </section-->
    <!--SPONSORS SECTION END-->
    <br />
    <section>
        <div class="container">
            <div class="row">
                <div class="col-md-9">
                  {% block content %}
                    {% endblock content %}
                    <!--BLOG ONE END -->
                   <!-- <nav>
                        <ul class="pagination">
                            <li class="disabled"><a href="#"><span aria-hidden="true">&laquo;</span><span class="sr-only">Previous</span></a></li>
                            <li class="active"><a href="#">1 <span class="sr-only">(current)</span></a></li>
                            <li><a href="#">2 <span class="sr-only"></span></a></li>
                            <li><a href="#">3 <span class="sr-only"></span></a></li>
                            <li><a href="#">4 <span class="sr-only"></span></a></li>
                            <li><a href="#">5 <span class="sr-only"></span></a></li>
                            <li><a href="#"><span aria-hidden="true">&raquo;</span><span class="sr-only">Next</span></a></li>
                        </ul>
                    </nav> -->
                     <!--PAGING  END -->
                {% include "paginator.html" %}
                </div>
                <div class="col-md-3">
                  <br/>
                  <form class="form-inline" method="get" action="{% url "blog:search" %}">{% csrf_token %}
                    <div class="form-group">
                    <input class="form-control" name="key" type="search" placeholder="搜索" required>
                    <button class="btn btn-primary" type="submit">搜索</button>
                    </div>
                  </form>
                    <br/>
                    <ul class="list-group">
                        <li class="list-group-item">
                            <strong>文章分类</strong>
                        </li>
                        {% get_categories as category_list %}
                        {% for category in category_list %}
                        <li class="list-group-item">
                          <a href="{% url 'blog:category' category.pk %}">{{category.name}}</a>
                        </li>
                        {% endfor %}
                        <li class="list-group-item">
                            <strong>文章标签</strong>
                        </li>
                        {% tags as tag_list %}
                        {% for tag in tag_list %}
                        <li class="list-group-item">
                          <a href="{% url 'blog:tags' tag.pk %}">{{tag.name}}</a>
                        </li>
                        {% endfor %}
                    </ul>
                    <br />

                    <ul class="list-group">
                        <li class="list-group-item">
                          <strong>最新文章</strong>
                        </li>
                          {% get_recent_posts as recent_post_list %}
                          {% for post in recent_post_list %}
                        <li class="list-group-item">
                          <a href="{{ post.get_absolute_url  }}">{{post.title}}
                            </a>
                        </li>
                        {% endfor %}
                    </ul>

                    <br />
                   <!-- <ul class="list-group">
                        <li class="list-group-item">
                            <strong>文章归档</strong>
                        </li>
                        {% archives as date_list %}
                        {% for date in date_list %}
                        <li class="list-group-item">
                          <a href="{% url 'blog:archives' date.year date.month %}">{{date.year}} 年 {{date.month}} 月</a>
                        </li>
                        {% endfor %}
                    </ul> -->
                    <div>
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h3 class="panel-title">Subscribe For Updates</h3>
                            </div>
                            <div class="panel-body">
                                <input type="text" class="form-control" placeholder="Your Email" />
                                <hr />
                                <a href="#" class="btn btn-info btn-sm btn-block">subscribe</a>
                            </div>
                        </div>
                    </div>
                </div>



            </div>
        </div>
    </section>
    <hr />
    <div class="container">
        <div class="row">
            <div class="col-md-12 text-center set-foot">
                &copy 2017 Colin Hu <a href="https://github.com/ttbug">Github</a> 一蓑烟雨任平生
            </div>
        </div>
    </div>

</body>
</html>

blogproject/templates/blog/detail.html
{% extends "base.html" %}  
{% load custom_markdown %}
{% block content %}
<div class="blog-main">
      <div class="heading-blog">
        <h2>{{post.title}}</h2>
      </div>
      <div class="blog-info">
         <span class="label label-primary">Posted on {{post.create_time}}</span>
         <span class="label label-success">In {{post.category}}</span>
         <span class="label label-danger">By {{post.author}}</span>
         <span class="label label-info">
           <i class="fa fa-thumbs-up"></i>+ {{post.views}}
          <!--i class="fa fa-thumbs-down"></i-->
         </span>
       </div>
       <div class="blog-txt">
           <p>{{post.body | custom_markdown}}</p>
       </div>
</div>
<br />
<div class="bdsharebuttonbox"><a href="#" class="bds_more" data-cmd="more">分享到：</a><a href="#" class="bds_qzone" data-cmd="qzone" title="分享到QQ空间">QQ空间</a><a href="#" class="bds_tsina" data-cmd="tsina" title="分享到新浪微博">新浪微博</a><a href="#" class="bds_tqq" data-cmd="tqq" title="分享到腾讯微博">腾讯微博</a><a href="#" class="bds_renren" data-cmd="renren" title="分享到人人网">人人网</a><a href="#" class="bds_weixin" data-cmd="weixin" title="分享到微信">微信</a></div>
<script>window._bd_share_config={"common":{"bdSnsKey":{},"bdText":"","bdMini":"1","bdMiniList":false,"bdPic":"","bdStyle":"1","bdSize":"16"},"share":{"bdSize":16},"image":{"viewList":["qzone","tsina","tqq","renren","weixin"],"viewText":"分享到：","viewSize":"16"}};with(document)0[(getElementsByTagName('head')[0]||body).appendChild(createElement('script')).src='http://bdimg.share.baidu.com/static/api/js/share.js?v=89860593.js?cdnversion='+~(-new Date()/36e5)];</script>
<!-- JiaThis Button BEGIN -->
<!--div class="jiathis_style">
    <span class="jiathis_txt">分享到：</span>
    <a class="jiathis_button_qzone">QQ空间</a>
    <a class="jiathis_button_tsina">新浪微博</a>
    <a class="jiathis_button_tqq">腾讯微博</a>
    <a class="jiathis_button_weixin">微信</a>
    <a href="http://www.jiathis.com/share?uid=2130726" class="jiathis jiathis_txt jiathis_separator jtico jtico_jiathis" target="_blank">更多</a>
    <a class="jiathis_counter_style"></a>
</div>
<script type="text/javascript">
var jiathis_config = {data_track_clickback:'true'};
</script>
<script type="text/javascript" src="http://v3.jiathis.com/code/jia.js?uid=2130726" charset="utf-8"></script-->
<!-- JiaThis Button END -->
 <!-- UY BEGIN -->
<div id="uyan_frame"></div>
<script type="text/javascript" src="http://v2.uyan.cc/code/uyan.js?uid=2130726"></script>
<!-- UY END -->
{% endblock content %}

blogproject/templates/blog/index.html
{% extends "base.html" %}
{% block content%}
{% for post in post_list %}
     <div class="blog-main">
     <div class="heading-blog">
        <h3><a href="{{post.get_absolute_url}}">{{post.title}}</a><h3>
     </div>
     <div class="blog-info">
        <span class="label label-primary">Posted on {{post.create_time}}</span>
         <span class="label label-success">In {{post.category}}</span>
         <span class="label label-danger">By {{post.author}}</span>
         <span class="label label-info">
           <i class="fa fa-thumbs-up"></i>+ {{post.views}}
           <!--i class="fa fa-thumbs-down"></i-->
         </span>
     </div>
     <div class="blog-txt">
        <p>{{post.excerpt}}</p>
     </div>
  </div>
{% endfor %}
{% endblock content%}

blogproject/templates/blog/results.html
{% extends "base.html" %}
{% block content%}
{% if err_msg %}
    <p>{{ err_msg }}<p>
{% endif%}
{% for post in post_list %}
     <div class="blog-main">
     <div class="heading-blog">
        <h2><a href="{{post.get_absolute_url}}">{{post.title}}</a><h2>
     </div>
     <div class="blog-info">
        <span class="label label-primary">Posted on {{post.create_time}}</span>
         <span class="label label-success">In {{post.category}}</span>
         <span class="label label-danger">By {{post.author}}</span>
         <span class="label label-info">
           <i class="fa fa-thumbs-up"></i>+ 10
           <i class="fa fa-thumbs-down"></i>-3
         </span>
     </div>
     <div class="blog-txt">
        <p>{{post.excerpt}}</p>
     </div>
  </div>
{% empty %}
  <div class="no-post">
    没有搜索到符合条件的文章
  </div>
{% endfor %}
{% endblock content%}

blogproject/templates/paginator.html
<nav>
  <ul class="pagination">
    {% if pagination_data.has_previous %}
    <li>
    <a href="?page_no=1" aria-label="Previous">
        <span aria-hidden="true">首页</span>
      </a>
    </li>
    <li>
      <a href="?page_no={{ pagination_data.previous_link }}" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
      </a>
    </li>
    {% endif %}
    {% for no in pagination_data.page_links  %}  
      <li{% if pagination_data.current_no == no %} class="active"{% endif %}>
        <a href="?page_no={{ no }}">{{ no }}</a>
      </li>
    {% endfor %}
    {% if pagination_data.has_next %}
    <li>
      <a href="?page_no={{ pagination_data.next_link }}" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
      </a>
    </li>
    <li>
      <a href="?page_no={{ pagination_data.page_cnt }}" aria-label="Next">
        <span aria-hidden="true">尾页</span>
      </a>
    </li>
    {% endif %}
  </ul>
</nav>

blogproject/templates/usercenter/activate_status.html
{% extends "base.html" %}
{% block content %}
<div class="alert alert-info" role="alert">
  <strong>{{msg}}</strong>
</div>
{% endblock %}

blogproject/templates/usercenter/register.html
{% extends "base.html" %}
{% block content %}
{% if msg %}
<div class="alert alert-danger" role="alert">{{msg}}</div>
{% endif %}
<br/><br/>
<div class="col-sm-2">
</div>
<div class="col-sm-8">
<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">用户注册</h3>
  </div>
  <div class="panel-body">
    <form method="POST">{% csrf_token %}
      <div class="input-group">
        <span class="input-group-addon">用户名 </span>
        <input type="text" class="form-control" id="id_name" placeholder="用户名" name="username">
      </div>
      <br/>
      <div class="input-group">
        <span class="input-group-addon">密码  </span>
        <input type="password" class="form-control" id="id_password" placeholder="密码" name="passwd">
      </div>
      <br/>
      <div class="input-group">
        <span class="input-group-addon">确认密码</span>
        <input type="password" class="form-control" id="id_password" placeholder="确认密码" name="re_passwd">
      </div>
      <br/>
      <div class="input-group">
        <span class="input-group-addon">邮箱  </span>
        <input type="email" class="form-control" id="id_email" placeholder="邮箱" name="email">
      </div>
      <br/>
      <input class="btn btn-primary" type="submit" value="注册">
    </form>
  </div>
  <div class="panel-footer">
    <a href="accounts/login">已有账号？点击此处去登陆吧......</a>
  </div>
</div>
</div>
<div class="col-sm-2">
</div>
{% endblock %}

blogproject/templates/usercenter/register_success.html
{% extends "base.html" %}
{% block content %}
<div class="alert alert-success" role="alert">
  <strong>{{msg}}</strong>
</div>
{% endblock %}